import { fingerprint } from "./fingerprint.ts";
import {
  RENDER_GENERATOR,
  type RenderContext,
  type RenderKind,
  type RenderProvenance,
  type RenderedDocument,
} from "./types.ts";

/** Comment prefix that keeps each document valid in its own format. */
const COMMENT_PREFIX: Readonly<Record<RenderKind, string>> = Object.freeze({
  progress: "",
  gantt: "%% ",
});

const RENDER_KINDS: readonly RenderKind[] = Object.freeze(["progress", "gantt"]);

const NOTICE =
  "generated by @arc/workflow-core; edit the workflow source, not this file";

const ABSENT_SOURCE = "null";

const GENERATED_AT =
  /^(\d{4})-(\d{2})-(\d{2})(?:[T ](\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-](\d{2}):(\d{2}))?)?$/u;

const HEADER_FIELDS = Object.freeze([
  "arc-render",
  "slug",
  "generator",
  "generated-at",
  "source",
  "source-fingerprint",
  "content-fingerprint",
  "notice",
] as const);

function isRenderKind(value: string): value is RenderKind {
  return (RENDER_KINDS as readonly string[]).includes(value);
}

/** Whether a Gregorian year includes February 29. */
function isLeapYear(year: number): boolean {
  return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
}

/** Validate and return the date portion of an ISO-like render value. */
export function datePortion(value: string, field: string): string {
  const match = GENERATED_AT.exec(value);
  if (match === null) {
    throw new TypeError(
      `${field} must be YYYY-MM-DD or an ISO-like timestamp, received ${JSON.stringify(value)}`,
    );
  }

  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = match[4] === undefined ? null : Number(match[4]);
  const minute = match[5] === undefined ? null : Number(match[5]);
  const second = match[6] === undefined ? null : Number(match[6]);
  const offsetHour = match[7] === undefined ? null : Number(match[7]);
  const offsetMinute = match[8] === undefined ? null : Number(match[8]);
  const daysInMonth = [
    31,
    isLeapYear(year) ? 29 : 28,
    31,
    30,
    31,
    30,
    31,
    31,
    30,
    31,
    30,
    31,
  ];
  const valid =
    month >= 1 &&
    month <= 12 &&
    day >= 1 &&
    day <= (daysInMonth[month - 1] ?? 0) &&
    (hour === null || hour <= 23) &&
    (minute === null || minute <= 59) &&
    (second === null || second <= 59) &&
    (offsetHour === null || offsetHour <= 23) &&
    (offsetMinute === null || offsetMinute <= 59);

  if (!valid) {
    throw new TypeError(
      `${field} must contain a possible calendar date and time, received ${JSON.stringify(value)}`,
    );
  }

  return value.slice(0, 10);
}

/** Encode nullable source provenance without reserving any string sentinel. */
function encodeSource(source: string | null): string {
  return source === null ? ABSENT_SOURCE : JSON.stringify(source);
}

/** Decode source provenance, rejecting malformed or non-string JSON values. */
function decodeSource(value: string): string | null | undefined {
  if (value === ABSENT_SOURCE) return null;
  try {
    const parsed: unknown = JSON.parse(value);
    return typeof parsed === "string" ? parsed : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Assemble a document from its body: fingerprints the body, prepends the
 * provenance header, and returns the exact text a writer should persist.
 * Pure — nothing here reads or writes the filesystem.
 */
export function buildDocument(input: {
  kind: RenderKind;
  slug: string;
  context: RenderContext;
  sourceFingerprint: string;
  body: string;
}): RenderedDocument {
  const { kind, slug, context, sourceFingerprint, body } = input;
  datePortion(context.generated_at, "render context generated_at");
  if (/[\r\n]/.test(slug)) {
    throw new RangeError("render slug must not contain newlines");
  }

  const provenance: RenderProvenance = {
    kind,
    slug,
    generator: RENDER_GENERATOR,
    generated_at: context.generated_at,
    source: context.source ?? null,
    source_fingerprint: sourceFingerprint,
    content_fingerprint: fingerprint(body),
  };

  const prefix = COMMENT_PREFIX[kind];
  const header = [
    ["arc-render", provenance.kind],
    ["slug", provenance.slug],
    ["generator", provenance.generator],
    ["generated-at", provenance.generated_at],
    ["source", encodeSource(provenance.source)],
    ["source-fingerprint", provenance.source_fingerprint],
    ["content-fingerprint", provenance.content_fingerprint],
    ["notice", NOTICE],
  ]
    .map(([key, value]) => `${prefix}${key}: ${value}`)
    .join("\n");

  return { kind, text: `${header}\n\n${body}`, body, provenance };
}

/** A generated document taken apart again. */
export interface ParsedDocument {
  provenance: RenderProvenance;
  body: string;
}

/**
 * Recover provenance and body from existing document text. Returns null when
 * the text carries no recognizable header, which callers must treat as
 * "not ours, do not overwrite".
 */
export function parseDocument(text: string): ParsedDocument | null {
  const lines = text.split("\n");
  const first = lines[0] ?? "";
  const kind = RENDER_KINDS.find(
    (candidate) =>
      first === `${COMMENT_PREFIX[candidate]}arc-render: ${candidate}`,
  );
  if (kind === undefined) return null;

  const prefix = COMMENT_PREFIX[kind];
  const values = new Map<string, string>();
  for (const [index, key] of HEADER_FIELDS.entries()) {
    const line = lines[index];
    if (line === undefined) return null;
    if (key === "notice") {
      if (line !== `${prefix}notice: ${NOTICE}`) return null;
      values.set(key, NOTICE);
      continue;
    }

    const start = `${prefix}${key}: `;
    if (!line.startsWith(start)) return null;
    const value = line.slice(start.length);
    if (value === "") return null;
    values.set(key, value);
  }

  // Exactly one blank line separates the exact eight-line header from the
  // body. This rejects reordered, duplicated, missing, and unknown fields.
  if (lines[HEADER_FIELDS.length] !== "") return null;

  const slug = values.get("slug");
  const generator = values.get("generator");
  const generatedAt = values.get("generated-at");
  const source = values.get("source");
  const sourceFingerprint = values.get("source-fingerprint");
  const contentFingerprint = values.get("content-fingerprint");

  if (
    slug === undefined ||
    generator === undefined ||
    generatedAt === undefined ||
    source === undefined ||
    sourceFingerprint === undefined ||
    contentFingerprint === undefined ||
    !isRenderKind(kind)
  ) {
    return null;
  }

  try {
    datePortion(generatedAt, "document generated-at");
  } catch {
    return null;
  }

  const decodedSource = decodeSource(source);
  if (decodedSource === undefined) return null;

  return {
    provenance: {
      kind,
      slug,
      generator,
      generated_at: generatedAt,
      source: decodedSource,
      source_fingerprint: sourceFingerprint,
      content_fingerprint: contentFingerprint,
    },
    body: lines.slice(HEADER_FIELDS.length + 1).join("\n"),
  };
}
